"""Select and prepare local KH3 Xion recordings for the native voice module.

Input: AudioMog-decoded English Xion projects containing TrackUsers.txt and
PCM16 WAVs, plus a reviewed JSON selection with cue, groups, and evidence.
Never selects a recording by a guessed track number. No resampling, trimming,
pitch change, synthetic speech, or per-clip loudness normalization is applied.
"""
from __future__ import annotations
import argparse
import array
import hashlib
import json
import math
from pathlib import Path
import re
import sys
import wave

GROUPS = {"AttackLight", "AttackStrong", "Jump", "Exertion", "HurtLight",
          "HurtHeavy", "Gasp", "Scream", "Breath", "Soft"}


def prepare(decoded: Path | list[Path], selection: Path, project: Path) -> dict:
    cue_tracks: dict[str, Path] = {}
    projects = [decoded] if isinstance(decoded, Path) else decoded
    for folder in projects:
        for line in (folder / "TrackUsers.txt").read_text(encoding="utf-8-sig").splitlines():
            if not line.strip():
                continue
            track, cues = line.split("users:", 1)
            source = folder / (Path(track.split(",", 1)[0].strip()).stem + ".wav")
            for cue in cues.split(","):
                cue = cue.strip()
                if cue:
                    assert cue not in cue_tracks, f"Ambiguous cue {cue}"
                    cue_tracks[cue] = source
    reviewed = json.loads(selection.read_text(encoding="utf-8-sig"))
    entries = reviewed["clips"]
    assert entries and sum(len(item["groups"]) for item in entries) <= 64
    prepared = []
    definitions = []
    destination = project / "res/xion/voice"
    destination.mkdir(parents=True, exist_ok=True)
    seen = set()
    for entry in entries:
        cue = entry["cue"]
        assert re.fullmatch(r"(?:bt215\d{4}|kg[0-9a-z]+)xi0", cue), f"Unexpected Xion cue {cue}"
        assert cue not in seen, f"Duplicate cue {cue}"
        seen.add(cue)
        assert entry.get("evidence"), "Record source evidence for every selected cue"
        assert entry["groups"] and set(entry["groups"]) <= GROUPS
        volume = float(entry.get("source_volume", 1.0))
        assert math.isfinite(volume) and 0 < volume <= 4, "Invalid source cue volume"
        source = cue_tracks[cue]
        with wave.open(str(source), "rb") as inp:
            channels, width, rate = inp.getnchannels(), inp.getsampwidth(), inp.getframerate()
            frames = inp.getnframes()
            assert width == 2 and channels in (1, 2) and frames > 0
            assert inp.getcomptype() == "NONE" and 8000 <= rate <= 192000
            pcm = array.array("h", inp.readframes(frames))
        if sys.byteorder != "little":
            pcm.byteswap()
        assert len(pcm) == frames * channels
        if channels == 2:
            pcm = array.array("h", (round((pcm[i] + pcm[i + 1]) / 2)
                                    for i in range(0, len(pcm), 2)))
        peak = max(abs(sample) for sample in pcm)
        assert peak > 0, f"Silent decoded recording: {cue}"
        out = destination / f"{cue}.wav"
        native_pcm = array.array("h", pcm)
        if sys.byteorder != "little":
            native_pcm.byteswap()
        with wave.open(str(out), "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)
            wav.setframerate(rate)
            wav.writeframes(native_pcm.tobytes())
        with wave.open(str(out), "rb") as verify:
            assert verify.getnchannels() == 1 and verify.getsampwidth() == 2
            assert verify.getnframes() == frames and verify.getframerate() == rate
            assert verify.readframes(frames) == native_pcm.tobytes()
        relative = out.relative_to(project).as_posix()
        definitions.extend((relative, group, volume) for group in entry["groups"])
        prepared.append({"cue": cue, "decoded_project": source.parent.name, "decoded_track": source.name,
                         "groups": entry["groups"], "evidence": entry["evidence"],
                         "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                         "file": relative, "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
                         "source_channels": channels, "sample_rate": rate,
                         "frames": frames, "seconds": frames / rate,
                         "peak_pcm16": peak, "gain": 1.0, "source_volume": volume})
    header = """#pragma once
// Generated by tools/prepare_xion_voice.py from reviewed local KH3 cue data.
#include "character_voice_mapping.hpp"
namespace kingdom::character_voice {
inline constexpr ClipDefinition kXionClips[]{
"""
    header += "".join(f'    {{"{path}",Group::{group},{volume:.8f}f}},\n' for path, group, volume in definitions)
    header += "};\n} // namespace kingdom::character_voice\n"
    (project / "src/character_voice_clips.hpp").write_text(header, encoding="utf-8")
    provenance = {"source_banks": sorted({clip["decoded_project"] for clip in prepared}), "language": "English",
                  "conversion":
                  "PCM16 mono; stereo (L+R)/2 when necessary; original sample rate, duration, pitch and gain.",
                  "classification": reviewed.get("classification", "Source asset usage; no listening claim."),
                  "clips": prepared}
    (project / "tools/xion-voice-provenance.json").write_text(
        json.dumps(provenance, indent=2), encoding="utf-8")
    return {"files": len(prepared), "definitions": len(definitions),
            "groups": sorted({g for _, g, _ in definitions}),
            "bytes": sum((project / clip["file"]).stat().st_size for clip in prepared)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--decoded", required=True, type=Path, nargs="+")
    parser.add_argument("--selection", required=True, type=Path)
    parser.add_argument("--project", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    print(json.dumps(prepare(args.decoded, args.selection, args.project), indent=2))
