#pragma once
// Generated by tools/prepare_xion_voice.py from reviewed local KH3 cue data.
#include "character_voice_mapping.hpp"
namespace kingdom::character_voice {
inline constexpr ClipDefinition kXionClips[]{
    {"res/xion/voice/bt2150010xi0.wav",Group::HurtLight,0.50000000f},
    {"res/xion/voice/bt2150020xi0.wav",Group::HurtLight,0.50000000f},
    {"res/xion/voice/bt2150030xi0.wav",Group::Scream,0.50000000f},
    {"res/xion/voice/bt2150040xi0.wav",Group::HurtHeavy,0.50000000f},
    {"res/xion/voice/bt2150050xi0.wav",Group::HurtHeavy,0.50000000f},
    {"res/xion/voice/bt2150060xi0.wav",Group::AttackLight,0.50000000f},
    {"res/xion/voice/bt2150060xi0.wav",Group::Jump,0.50000000f},
    {"res/xion/voice/bt2150060xi0.wav",Group::Exertion,0.50000000f},
    {"res/xion/voice/bt2150070xi0.wav",Group::AttackLight,0.50000000f},
    {"res/xion/voice/bt2150070xi0.wav",Group::Jump,0.50000000f},
    {"res/xion/voice/bt2150070xi0.wav",Group::Exertion,0.50000000f},
    {"res/xion/voice/bt2150080xi0.wav",Group::AttackLight,0.50000000f},
    {"res/xion/voice/bt2150080xi0.wav",Group::Jump,0.50000000f},
    {"res/xion/voice/bt2150080xi0.wav",Group::Exertion,0.50000000f},
    {"res/xion/voice/bt2150090xi0.wav",Group::AttackStrong,0.50000000f},
    {"res/xion/voice/bt2150100xi0.wav",Group::AttackStrong,0.50000000f},
    {"res/xion/voice/kg8720262xi0.wav",Group::Breath,0.64999998f},
    {"res/xion/voice/kg8720263xi0.wav",Group::Soft,0.64999998f},
    {"res/xion/voice/kg8720279xi0.wav",Group::Gasp,0.64999998f},
    {"res/xion/voice/kg8720280xi0.wav",Group::Exertion,0.64999998f},
};
} // namespace kingdom::character_voice
